# Generated by Django 2.0.4 on 2018-05-16 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180420_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='logdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
